---

#The following two plays are only required until we get Jenkins added to Aptly.


- name: Add Jenkins Apt key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present




- name: rm aptly locks
  file:
    name: /var/lib/dpkg/lock
    state: absent




- name: add jenkins repo
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present




- name: install prereqs
  apt:
    name: openjdk-8-jdk,nginx
    update_cache: yes
    state: present



- name: install jekins
  apt:
    name: jenkins
    update_cache: yes
    state: present



- name: Add jenkins user to sudo
  user:
    name: jenkins
    group: sudo




- name: Create a 2048-bit SSH key for user jenkins
  user:
    name: jenkins
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa



- name: fetch jenkins public ssh keys
  shell: cat /home/jenkins/.ssh/id_rsa.pub
  register: ssh_keys




- name: deploy jenkins keys on all servers
  authorized_key:
    user: jenkins
    key: "{{ item[0] }}"
  delegate_to: "{{ item[1] }}"
  with_nested:
    - "{{ ssh_keys.stdout }}"
    - "{{groups['jenkins']}}"



- name: enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'



- name: copy nginx template
  template:
    src: roles/jenkins_master/templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx




- name: Add the user 'nginx' and a primary group of 'admin'
  user:
    name: nginx
    comment: nginx



- name: start nginx
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: nginx



#Only want this pause to run during the initial deployment
- name: pause to allow for default plugin installation to complete
  pause:
    prompt: "Browse to http://{{inventory_hostname}}:8080, enter the password in the Jenkins installation window then install the recommended plugins"
    echo: yes
    minutes: 10




- name: "Build hosts file - ONLY NEEDED FOR TEST ENVIRONMENTS"
  lineinfile:
    dest: /etc/hosts
    line: "{% for host in groups['jenkins-agent'] %}{{  hostvars[host].ansible_host }} {{host}} {% endfor %}"
    state: present








