---


- name: Ubuntu - Add jenkins user to sudo
  user:
    name: jenkins
    group: sudo
    shell: /bin/bash



- name: enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'



- name: "Build hosts file - ONLY NEEDED FOR TEST ENVIRONMENTS"
  lineinfile:
    dest: /etc/hosts
    line: "{% for host in groups['jenkins-master'] %}{{  hostvars[host].ansible_host }} {{host}} {% endfor %}"
    state: present

